### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-AmeliReyesHernandez#1]
[INFOGRAFIA Ameli Reyes Hernandez 4bs.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-AmeliReyesHernandez/files/14588289/INFOGRAFIA.Ameli.Reyes.Hernandez.4bs.pdf)

**Comment by EdgarExa** [comment]
20% de 20 bien hecho

**Comment by josealfredo79** [comment]
BIen hecho y revisado...
